import { Nunito } from 'next/font/google'
import Navbar from './components/navbar/Navbar'

import './globals.css'
import ClientOnly from './components/ClientOnly'
import Modal from './components/modals/Modal'

const nunito = Nunito({
  subsets: ['latin'],
})

export const metadata = {
  title: 'AirBnb',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
        <ClientOnly>
          {/* <Modal 
            isOpen={true}
            onClose={() => alert('test')}
            onSubmit={() => alert('test')}
            title="test"
            actionLabel="test"
          /> */}
          <Navbar />
        </ClientOnly>
        {children}
      </body>
    </html>
  )
}
